// Pre-generated bindings for ThreadX 6.4.1
// Generated by: bindgen 0.69.5
// Target: armv7r-none-eabihf (--target=arm -mthumb -mcpu=cortex-r5 -mfloat-abi=hard)
// Regenerate: cargo build --release --features threadx-sys/bindgen

pub const TX_MAX_PRIORITIES: u32 = 32;
pub const TX_MINIMUM_STACK: u32 = 200;
pub const TX_TIMER_THREAD_STACK_SIZE: u32 = 1024;
pub const TX_TIMER_THREAD_PRIORITY: u32 = 0;
pub const TX_INT_DISABLE: u32 = 128;
pub const TX_INT_ENABLE: u32 = 0;
pub const TX_TRACE_TIME_MASK: u32 = 4294967295;
pub const TX_FIQ_ENABLED: u32 = 0;
pub const TX_IRQ_NESTING_ENABLED: u32 = 0;
pub const TX_FIQ_NESTING_ENABLED: u32 = 0;
pub const TX_PORT_SPECIFIC_BUILD_OPTIONS: u32 = 0;
pub const TX_TIMER_TICKS_PER_SECOND: u32 = 100;
pub const TX_TRACE_USER_EVENT_START: u32 = 4096;
pub const TX_TRACE_USER_EVENT_END: u32 = 65535;
pub const TX_TRACE_ALL_EVENTS: u32 = 2047;
pub const TX_TRACE_INTERNAL_EVENTS: u32 = 1;
pub const TX_TRACE_BLOCK_POOL_EVENTS: u32 = 2;
pub const TX_TRACE_BYTE_POOL_EVENTS: u32 = 4;
pub const TX_TRACE_EVENT_FLAGS_EVENTS: u32 = 8;
pub const TX_TRACE_INTERRUPT_CONTROL_EVENT: u32 = 16;
pub const TX_TRACE_MUTEX_EVENTS: u32 = 32;
pub const TX_TRACE_QUEUE_EVENTS: u32 = 64;
pub const TX_TRACE_SEMAPHORE_EVENTS: u32 = 128;
pub const TX_TRACE_THREAD_EVENTS: u32 = 256;
pub const TX_TRACE_TIME_EVENTS: u32 = 512;
pub const TX_TRACE_TIMER_EVENTS: u32 = 1024;
pub const TX_TRACE_USER_EVENTS: u32 = 2147483648;
pub type CHAR = ::core::ffi::c_char;
pub type UCHAR = ::core::ffi::c_uchar;
pub type UINT = ::core::ffi::c_uint;
pub type ULONG = ::core::ffi::c_ulong;
extern "C" {
    pub fn _tx_thread_interrupt_disable() -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn _tx_thread_interrupt_restore(old_posture: UINT) -> ::core::ffi::c_uint;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TX_TIMER_INTERNAL_STRUCT {
    pub tx_timer_internal_remaining_ticks: ULONG,
    pub tx_timer_internal_re_initialize_ticks: ULONG,
    pub tx_timer_internal_timeout_function: ::core::option::Option<unsafe extern "C" fn(id: ULONG)>,
    pub tx_timer_internal_timeout_param: ULONG,
    pub tx_timer_internal_active_next: *mut TX_TIMER_INTERNAL_STRUCT,
    pub tx_timer_internal_active_previous: *mut TX_TIMER_INTERNAL_STRUCT,
    pub tx_timer_internal_list_head: *mut *mut TX_TIMER_INTERNAL_STRUCT,
}
#[test]
fn bindgen_test_layout_TX_TIMER_INTERNAL_STRUCT() {
    const UNINIT: ::core::mem::MaybeUninit<TX_TIMER_INTERNAL_STRUCT> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<TX_TIMER_INTERNAL_STRUCT>(),
        28usize,
        concat!("Size of: ", stringify!(TX_TIMER_INTERNAL_STRUCT))
    );
    assert_eq!(
        ::core::mem::align_of::<TX_TIMER_INTERNAL_STRUCT>(),
        4usize,
        concat!("Alignment of ", stringify!(TX_TIMER_INTERNAL_STRUCT))
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_timer_internal_remaining_ticks) as usize - ptr as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_TIMER_INTERNAL_STRUCT),
            "::",
            stringify!(tx_timer_internal_remaining_ticks)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_timer_internal_re_initialize_ticks) as usize
                - ptr as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_TIMER_INTERNAL_STRUCT),
            "::",
            stringify!(tx_timer_internal_re_initialize_ticks)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_timer_internal_timeout_function) as usize - ptr as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_TIMER_INTERNAL_STRUCT),
            "::",
            stringify!(tx_timer_internal_timeout_function)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_timer_internal_timeout_param) as usize - ptr as usize
        },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_TIMER_INTERNAL_STRUCT),
            "::",
            stringify!(tx_timer_internal_timeout_param)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_timer_internal_active_next) as usize - ptr as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_TIMER_INTERNAL_STRUCT),
            "::",
            stringify!(tx_timer_internal_active_next)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_timer_internal_active_previous) as usize - ptr as usize
        },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_TIMER_INTERNAL_STRUCT),
            "::",
            stringify!(tx_timer_internal_active_previous)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_timer_internal_list_head) as usize - ptr as usize
        },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_TIMER_INTERNAL_STRUCT),
            "::",
            stringify!(tx_timer_internal_list_head)
        )
    );
}
pub type TX_TIMER_INTERNAL = TX_TIMER_INTERNAL_STRUCT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TX_TIMER_STRUCT {
    pub tx_timer_id: ULONG,
    pub tx_timer_name: *mut CHAR,
    pub tx_timer_internal: TX_TIMER_INTERNAL,
    pub tx_timer_created_next: *mut TX_TIMER_STRUCT,
    pub tx_timer_created_previous: *mut TX_TIMER_STRUCT,
}
#[test]
fn bindgen_test_layout_TX_TIMER_STRUCT() {
    const UNINIT: ::core::mem::MaybeUninit<TX_TIMER_STRUCT> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<TX_TIMER_STRUCT>(),
        44usize,
        concat!("Size of: ", stringify!(TX_TIMER_STRUCT))
    );
    assert_eq!(
        ::core::mem::align_of::<TX_TIMER_STRUCT>(),
        4usize,
        concat!("Alignment of ", stringify!(TX_TIMER_STRUCT))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_timer_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_TIMER_STRUCT),
            "::",
            stringify!(tx_timer_id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_timer_name) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_TIMER_STRUCT),
            "::",
            stringify!(tx_timer_name)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_timer_internal) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_TIMER_STRUCT),
            "::",
            stringify!(tx_timer_internal)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_timer_created_next) as usize - ptr as usize },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_TIMER_STRUCT),
            "::",
            stringify!(tx_timer_created_next)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_timer_created_previous) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_TIMER_STRUCT),
            "::",
            stringify!(tx_timer_created_previous)
        )
    );
}
pub type TX_TIMER = TX_TIMER_STRUCT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TX_THREAD_STRUCT {
    pub tx_thread_id: ULONG,
    pub tx_thread_run_count: ULONG,
    pub tx_thread_stack_ptr: *mut ::core::ffi::c_void,
    pub tx_thread_stack_start: *mut ::core::ffi::c_void,
    pub tx_thread_stack_end: *mut ::core::ffi::c_void,
    pub tx_thread_stack_size: ULONG,
    pub tx_thread_time_slice: ULONG,
    pub tx_thread_new_time_slice: ULONG,
    pub tx_thread_ready_next: *mut TX_THREAD_STRUCT,
    pub tx_thread_ready_previous: *mut TX_THREAD_STRUCT,
    pub tx_thread_name: *mut CHAR,
    pub tx_thread_priority: UINT,
    pub tx_thread_state: UINT,
    pub tx_thread_delayed_suspend: UINT,
    pub tx_thread_suspending: UINT,
    pub tx_thread_preempt_threshold: UINT,
    pub tx_thread_schedule_hook:
        ::core::option::Option<unsafe extern "C" fn(thread_ptr: *mut TX_THREAD_STRUCT, id: ULONG)>,
    pub tx_thread_entry: ::core::option::Option<unsafe extern "C" fn(id: ULONG)>,
    pub tx_thread_entry_parameter: ULONG,
    pub tx_thread_timer: TX_TIMER_INTERNAL,
    pub tx_thread_suspend_cleanup: ::core::option::Option<
        unsafe extern "C" fn(thread_ptr: *mut TX_THREAD_STRUCT, suspension_sequence: ULONG),
    >,
    pub tx_thread_suspend_control_block: *mut ::core::ffi::c_void,
    pub tx_thread_suspended_next: *mut TX_THREAD_STRUCT,
    pub tx_thread_suspended_previous: *mut TX_THREAD_STRUCT,
    pub tx_thread_suspend_info: ULONG,
    pub tx_thread_additional_suspend_info: *mut ::core::ffi::c_void,
    pub tx_thread_suspend_option: UINT,
    pub tx_thread_suspend_status: UINT,
    pub tx_thread_created_next: *mut TX_THREAD_STRUCT,
    pub tx_thread_created_previous: *mut TX_THREAD_STRUCT,
    pub tx_thread_filex_ptr: *mut ::core::ffi::c_void,
    pub tx_thread_user_priority: UINT,
    pub tx_thread_user_preempt_threshold: UINT,
    pub tx_thread_inherit_priority: UINT,
    pub tx_thread_owned_mutex_count: UINT,
    pub tx_thread_owned_mutex_list: *mut TX_MUTEX_STRUCT,
    pub tx_thread_stack_highest_ptr: *mut ::core::ffi::c_void,
    pub tx_thread_entry_exit_notify: ::core::option::Option<
        unsafe extern "C" fn(thread_ptr: *mut TX_THREAD_STRUCT, type_: UINT),
    >,
    pub tx_thread_suspension_sequence: ULONG,
}
#[test]
fn bindgen_test_layout_TX_THREAD_STRUCT() {
    const UNINIT: ::core::mem::MaybeUninit<TX_THREAD_STRUCT> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<TX_THREAD_STRUCT>(),
        180usize,
        concat!("Size of: ", stringify!(TX_THREAD_STRUCT))
    );
    assert_eq!(
        ::core::mem::align_of::<TX_THREAD_STRUCT>(),
        4usize,
        concat!("Alignment of ", stringify!(TX_THREAD_STRUCT))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_run_count) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_run_count)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_stack_ptr) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_stack_ptr)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_stack_start) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_stack_start)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_stack_end) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_stack_end)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_stack_size) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_stack_size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_time_slice) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_time_slice)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_new_time_slice) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_new_time_slice)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_ready_next) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_ready_next)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_ready_previous) as usize - ptr as usize },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_ready_previous)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_name) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_name)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_priority) as usize - ptr as usize },
        44usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_priority)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_state) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_state)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_delayed_suspend) as usize - ptr as usize },
        52usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_delayed_suspend)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_suspending) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_suspending)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_thread_preempt_threshold) as usize - ptr as usize
        },
        60usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_preempt_threshold)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_schedule_hook) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_schedule_hook)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_entry) as usize - ptr as usize },
        68usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_entry)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_entry_parameter) as usize - ptr as usize },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_entry_parameter)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_timer) as usize - ptr as usize },
        76usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_timer)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_suspend_cleanup) as usize - ptr as usize },
        104usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_suspend_cleanup)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_thread_suspend_control_block) as usize - ptr as usize
        },
        108usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_suspend_control_block)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_suspended_next) as usize - ptr as usize },
        112usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_suspended_next)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_thread_suspended_previous) as usize - ptr as usize
        },
        116usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_suspended_previous)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_suspend_info) as usize - ptr as usize },
        120usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_suspend_info)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_thread_additional_suspend_info) as usize - ptr as usize
        },
        124usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_additional_suspend_info)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_suspend_option) as usize - ptr as usize },
        128usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_suspend_option)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_suspend_status) as usize - ptr as usize },
        132usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_suspend_status)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_created_next) as usize - ptr as usize },
        136usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_created_next)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_created_previous) as usize - ptr as usize },
        140usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_created_previous)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_filex_ptr) as usize - ptr as usize },
        144usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_filex_ptr)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_user_priority) as usize - ptr as usize },
        148usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_user_priority)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_thread_user_preempt_threshold) as usize - ptr as usize
        },
        152usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_user_preempt_threshold)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_inherit_priority) as usize - ptr as usize },
        156usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_inherit_priority)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_thread_owned_mutex_count) as usize - ptr as usize
        },
        160usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_owned_mutex_count)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_thread_owned_mutex_list) as usize - ptr as usize },
        164usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_owned_mutex_list)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_thread_stack_highest_ptr) as usize - ptr as usize
        },
        168usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_stack_highest_ptr)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_thread_entry_exit_notify) as usize - ptr as usize
        },
        172usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_entry_exit_notify)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_thread_suspension_sequence) as usize - ptr as usize
        },
        176usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_THREAD_STRUCT),
            "::",
            stringify!(tx_thread_suspension_sequence)
        )
    );
}
pub type TX_THREAD = TX_THREAD_STRUCT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TX_BLOCK_POOL_STRUCT {
    pub tx_block_pool_id: ULONG,
    pub tx_block_pool_name: *mut CHAR,
    pub tx_block_pool_available: UINT,
    pub tx_block_pool_total: UINT,
    pub tx_block_pool_available_list: *mut UCHAR,
    pub tx_block_pool_start: *mut UCHAR,
    pub tx_block_pool_size: ULONG,
    pub tx_block_pool_block_size: UINT,
    pub tx_block_pool_suspension_list: *mut TX_THREAD_STRUCT,
    pub tx_block_pool_suspended_count: UINT,
    pub tx_block_pool_created_next: *mut TX_BLOCK_POOL_STRUCT,
    pub tx_block_pool_created_previous: *mut TX_BLOCK_POOL_STRUCT,
}
#[test]
fn bindgen_test_layout_TX_BLOCK_POOL_STRUCT() {
    const UNINIT: ::core::mem::MaybeUninit<TX_BLOCK_POOL_STRUCT> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<TX_BLOCK_POOL_STRUCT>(),
        48usize,
        concat!("Size of: ", stringify!(TX_BLOCK_POOL_STRUCT))
    );
    assert_eq!(
        ::core::mem::align_of::<TX_BLOCK_POOL_STRUCT>(),
        4usize,
        concat!("Alignment of ", stringify!(TX_BLOCK_POOL_STRUCT))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_block_pool_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BLOCK_POOL_STRUCT),
            "::",
            stringify!(tx_block_pool_id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_block_pool_name) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BLOCK_POOL_STRUCT),
            "::",
            stringify!(tx_block_pool_name)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_block_pool_available) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BLOCK_POOL_STRUCT),
            "::",
            stringify!(tx_block_pool_available)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_block_pool_total) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BLOCK_POOL_STRUCT),
            "::",
            stringify!(tx_block_pool_total)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_block_pool_available_list) as usize - ptr as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BLOCK_POOL_STRUCT),
            "::",
            stringify!(tx_block_pool_available_list)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_block_pool_start) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BLOCK_POOL_STRUCT),
            "::",
            stringify!(tx_block_pool_start)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_block_pool_size) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BLOCK_POOL_STRUCT),
            "::",
            stringify!(tx_block_pool_size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_block_pool_block_size) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BLOCK_POOL_STRUCT),
            "::",
            stringify!(tx_block_pool_block_size)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_block_pool_suspension_list) as usize - ptr as usize
        },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BLOCK_POOL_STRUCT),
            "::",
            stringify!(tx_block_pool_suspension_list)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_block_pool_suspended_count) as usize - ptr as usize
        },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BLOCK_POOL_STRUCT),
            "::",
            stringify!(tx_block_pool_suspended_count)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_block_pool_created_next) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BLOCK_POOL_STRUCT),
            "::",
            stringify!(tx_block_pool_created_next)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_block_pool_created_previous) as usize - ptr as usize
        },
        44usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BLOCK_POOL_STRUCT),
            "::",
            stringify!(tx_block_pool_created_previous)
        )
    );
}
pub type TX_BLOCK_POOL = TX_BLOCK_POOL_STRUCT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TX_BYTE_POOL_STRUCT {
    pub tx_byte_pool_id: ULONG,
    pub tx_byte_pool_name: *mut CHAR,
    pub tx_byte_pool_available: ULONG,
    pub tx_byte_pool_fragments: UINT,
    pub tx_byte_pool_list: *mut UCHAR,
    pub tx_byte_pool_search: *mut UCHAR,
    pub tx_byte_pool_start: *mut UCHAR,
    pub tx_byte_pool_size: ULONG,
    pub tx_byte_pool_owner: *mut TX_THREAD_STRUCT,
    pub tx_byte_pool_suspension_list: *mut TX_THREAD_STRUCT,
    pub tx_byte_pool_suspended_count: UINT,
    pub tx_byte_pool_created_next: *mut TX_BYTE_POOL_STRUCT,
    pub tx_byte_pool_created_previous: *mut TX_BYTE_POOL_STRUCT,
}
#[test]
fn bindgen_test_layout_TX_BYTE_POOL_STRUCT() {
    const UNINIT: ::core::mem::MaybeUninit<TX_BYTE_POOL_STRUCT> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<TX_BYTE_POOL_STRUCT>(),
        52usize,
        concat!("Size of: ", stringify!(TX_BYTE_POOL_STRUCT))
    );
    assert_eq!(
        ::core::mem::align_of::<TX_BYTE_POOL_STRUCT>(),
        4usize,
        concat!("Alignment of ", stringify!(TX_BYTE_POOL_STRUCT))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_byte_pool_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BYTE_POOL_STRUCT),
            "::",
            stringify!(tx_byte_pool_id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_byte_pool_name) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BYTE_POOL_STRUCT),
            "::",
            stringify!(tx_byte_pool_name)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_byte_pool_available) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BYTE_POOL_STRUCT),
            "::",
            stringify!(tx_byte_pool_available)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_byte_pool_fragments) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BYTE_POOL_STRUCT),
            "::",
            stringify!(tx_byte_pool_fragments)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_byte_pool_list) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BYTE_POOL_STRUCT),
            "::",
            stringify!(tx_byte_pool_list)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_byte_pool_search) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BYTE_POOL_STRUCT),
            "::",
            stringify!(tx_byte_pool_search)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_byte_pool_start) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BYTE_POOL_STRUCT),
            "::",
            stringify!(tx_byte_pool_start)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_byte_pool_size) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BYTE_POOL_STRUCT),
            "::",
            stringify!(tx_byte_pool_size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_byte_pool_owner) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BYTE_POOL_STRUCT),
            "::",
            stringify!(tx_byte_pool_owner)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_byte_pool_suspension_list) as usize - ptr as usize
        },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BYTE_POOL_STRUCT),
            "::",
            stringify!(tx_byte_pool_suspension_list)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_byte_pool_suspended_count) as usize - ptr as usize
        },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BYTE_POOL_STRUCT),
            "::",
            stringify!(tx_byte_pool_suspended_count)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_byte_pool_created_next) as usize - ptr as usize },
        44usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BYTE_POOL_STRUCT),
            "::",
            stringify!(tx_byte_pool_created_next)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_byte_pool_created_previous) as usize - ptr as usize
        },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_BYTE_POOL_STRUCT),
            "::",
            stringify!(tx_byte_pool_created_previous)
        )
    );
}
pub type TX_BYTE_POOL = TX_BYTE_POOL_STRUCT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TX_EVENT_FLAGS_GROUP_STRUCT {
    pub tx_event_flags_group_id: ULONG,
    pub tx_event_flags_group_name: *mut CHAR,
    pub tx_event_flags_group_current: ULONG,
    pub tx_event_flags_group_reset_search: UINT,
    pub tx_event_flags_group_suspension_list: *mut TX_THREAD_STRUCT,
    pub tx_event_flags_group_suspended_count: UINT,
    pub tx_event_flags_group_created_next: *mut TX_EVENT_FLAGS_GROUP_STRUCT,
    pub tx_event_flags_group_created_previous: *mut TX_EVENT_FLAGS_GROUP_STRUCT,
    pub tx_event_flags_group_delayed_clear: ULONG,
    pub tx_event_flags_group_set_notify:
        ::core::option::Option<unsafe extern "C" fn(group_ptr: *mut TX_EVENT_FLAGS_GROUP_STRUCT)>,
}
#[test]
fn bindgen_test_layout_TX_EVENT_FLAGS_GROUP_STRUCT() {
    const UNINIT: ::core::mem::MaybeUninit<TX_EVENT_FLAGS_GROUP_STRUCT> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<TX_EVENT_FLAGS_GROUP_STRUCT>(),
        40usize,
        concat!("Size of: ", stringify!(TX_EVENT_FLAGS_GROUP_STRUCT))
    );
    assert_eq!(
        ::core::mem::align_of::<TX_EVENT_FLAGS_GROUP_STRUCT>(),
        4usize,
        concat!("Alignment of ", stringify!(TX_EVENT_FLAGS_GROUP_STRUCT))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_event_flags_group_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_EVENT_FLAGS_GROUP_STRUCT),
            "::",
            stringify!(tx_event_flags_group_id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_event_flags_group_name) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_EVENT_FLAGS_GROUP_STRUCT),
            "::",
            stringify!(tx_event_flags_group_name)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_event_flags_group_current) as usize - ptr as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_EVENT_FLAGS_GROUP_STRUCT),
            "::",
            stringify!(tx_event_flags_group_current)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_event_flags_group_reset_search) as usize - ptr as usize
        },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_EVENT_FLAGS_GROUP_STRUCT),
            "::",
            stringify!(tx_event_flags_group_reset_search)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_event_flags_group_suspension_list) as usize
                - ptr as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_EVENT_FLAGS_GROUP_STRUCT),
            "::",
            stringify!(tx_event_flags_group_suspension_list)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_event_flags_group_suspended_count) as usize
                - ptr as usize
        },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_EVENT_FLAGS_GROUP_STRUCT),
            "::",
            stringify!(tx_event_flags_group_suspended_count)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_event_flags_group_created_next) as usize - ptr as usize
        },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_EVENT_FLAGS_GROUP_STRUCT),
            "::",
            stringify!(tx_event_flags_group_created_next)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_event_flags_group_created_previous) as usize
                - ptr as usize
        },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_EVENT_FLAGS_GROUP_STRUCT),
            "::",
            stringify!(tx_event_flags_group_created_previous)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_event_flags_group_delayed_clear) as usize - ptr as usize
        },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_EVENT_FLAGS_GROUP_STRUCT),
            "::",
            stringify!(tx_event_flags_group_delayed_clear)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_event_flags_group_set_notify) as usize - ptr as usize
        },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_EVENT_FLAGS_GROUP_STRUCT),
            "::",
            stringify!(tx_event_flags_group_set_notify)
        )
    );
}
pub type TX_EVENT_FLAGS_GROUP = TX_EVENT_FLAGS_GROUP_STRUCT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TX_MUTEX_STRUCT {
    pub tx_mutex_id: ULONG,
    pub tx_mutex_name: *mut CHAR,
    pub tx_mutex_ownership_count: UINT,
    pub tx_mutex_owner: *mut TX_THREAD,
    pub tx_mutex_inherit: UINT,
    pub tx_mutex_original_priority: UINT,
    pub tx_mutex_suspension_list: *mut TX_THREAD_STRUCT,
    pub tx_mutex_suspended_count: UINT,
    pub tx_mutex_created_next: *mut TX_MUTEX_STRUCT,
    pub tx_mutex_created_previous: *mut TX_MUTEX_STRUCT,
    pub tx_mutex_highest_priority_waiting: UINT,
    pub tx_mutex_owned_next: *mut TX_MUTEX_STRUCT,
    pub tx_mutex_owned_previous: *mut TX_MUTEX_STRUCT,
}
#[test]
fn bindgen_test_layout_TX_MUTEX_STRUCT() {
    const UNINIT: ::core::mem::MaybeUninit<TX_MUTEX_STRUCT> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<TX_MUTEX_STRUCT>(),
        52usize,
        concat!("Size of: ", stringify!(TX_MUTEX_STRUCT))
    );
    assert_eq!(
        ::core::mem::align_of::<TX_MUTEX_STRUCT>(),
        4usize,
        concat!("Alignment of ", stringify!(TX_MUTEX_STRUCT))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_mutex_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_MUTEX_STRUCT),
            "::",
            stringify!(tx_mutex_id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_mutex_name) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_MUTEX_STRUCT),
            "::",
            stringify!(tx_mutex_name)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_mutex_ownership_count) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_MUTEX_STRUCT),
            "::",
            stringify!(tx_mutex_ownership_count)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_mutex_owner) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_MUTEX_STRUCT),
            "::",
            stringify!(tx_mutex_owner)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_mutex_inherit) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_MUTEX_STRUCT),
            "::",
            stringify!(tx_mutex_inherit)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_mutex_original_priority) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_MUTEX_STRUCT),
            "::",
            stringify!(tx_mutex_original_priority)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_mutex_suspension_list) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_MUTEX_STRUCT),
            "::",
            stringify!(tx_mutex_suspension_list)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_mutex_suspended_count) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_MUTEX_STRUCT),
            "::",
            stringify!(tx_mutex_suspended_count)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_mutex_created_next) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_MUTEX_STRUCT),
            "::",
            stringify!(tx_mutex_created_next)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_mutex_created_previous) as usize - ptr as usize },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_MUTEX_STRUCT),
            "::",
            stringify!(tx_mutex_created_previous)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_mutex_highest_priority_waiting) as usize - ptr as usize
        },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_MUTEX_STRUCT),
            "::",
            stringify!(tx_mutex_highest_priority_waiting)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_mutex_owned_next) as usize - ptr as usize },
        44usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_MUTEX_STRUCT),
            "::",
            stringify!(tx_mutex_owned_next)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_mutex_owned_previous) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_MUTEX_STRUCT),
            "::",
            stringify!(tx_mutex_owned_previous)
        )
    );
}
pub type TX_MUTEX = TX_MUTEX_STRUCT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TX_QUEUE_STRUCT {
    pub tx_queue_id: ULONG,
    pub tx_queue_name: *mut CHAR,
    pub tx_queue_message_size: UINT,
    pub tx_queue_capacity: UINT,
    pub tx_queue_enqueued: UINT,
    pub tx_queue_available_storage: UINT,
    pub tx_queue_start: *mut ULONG,
    pub tx_queue_end: *mut ULONG,
    pub tx_queue_read: *mut ULONG,
    pub tx_queue_write: *mut ULONG,
    pub tx_queue_suspension_list: *mut TX_THREAD_STRUCT,
    pub tx_queue_suspended_count: UINT,
    pub tx_queue_created_next: *mut TX_QUEUE_STRUCT,
    pub tx_queue_created_previous: *mut TX_QUEUE_STRUCT,
    pub tx_queue_send_notify:
        ::core::option::Option<unsafe extern "C" fn(queue_ptr: *mut TX_QUEUE_STRUCT)>,
}
#[test]
fn bindgen_test_layout_TX_QUEUE_STRUCT() {
    const UNINIT: ::core::mem::MaybeUninit<TX_QUEUE_STRUCT> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<TX_QUEUE_STRUCT>(),
        60usize,
        concat!("Size of: ", stringify!(TX_QUEUE_STRUCT))
    );
    assert_eq!(
        ::core::mem::align_of::<TX_QUEUE_STRUCT>(),
        4usize,
        concat!("Alignment of ", stringify!(TX_QUEUE_STRUCT))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_name) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_name)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_message_size) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_message_size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_capacity) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_capacity)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_enqueued) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_enqueued)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_available_storage) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_available_storage)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_start) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_start)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_end) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_end)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_read) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_read)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_write) as usize - ptr as usize },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_write)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_suspension_list) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_suspension_list)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_suspended_count) as usize - ptr as usize },
        44usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_suspended_count)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_created_next) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_created_next)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_created_previous) as usize - ptr as usize },
        52usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_created_previous)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_queue_send_notify) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_QUEUE_STRUCT),
            "::",
            stringify!(tx_queue_send_notify)
        )
    );
}
pub type TX_QUEUE = TX_QUEUE_STRUCT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TX_SEMAPHORE_STRUCT {
    pub tx_semaphore_id: ULONG,
    pub tx_semaphore_name: *mut CHAR,
    pub tx_semaphore_count: ULONG,
    pub tx_semaphore_suspension_list: *mut TX_THREAD_STRUCT,
    pub tx_semaphore_suspended_count: UINT,
    pub tx_semaphore_created_next: *mut TX_SEMAPHORE_STRUCT,
    pub tx_semaphore_created_previous: *mut TX_SEMAPHORE_STRUCT,
    pub tx_semaphore_put_notify:
        ::core::option::Option<unsafe extern "C" fn(semaphore_ptr: *mut TX_SEMAPHORE_STRUCT)>,
}
#[test]
fn bindgen_test_layout_TX_SEMAPHORE_STRUCT() {
    const UNINIT: ::core::mem::MaybeUninit<TX_SEMAPHORE_STRUCT> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<TX_SEMAPHORE_STRUCT>(),
        32usize,
        concat!("Size of: ", stringify!(TX_SEMAPHORE_STRUCT))
    );
    assert_eq!(
        ::core::mem::align_of::<TX_SEMAPHORE_STRUCT>(),
        4usize,
        concat!("Alignment of ", stringify!(TX_SEMAPHORE_STRUCT))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_semaphore_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_SEMAPHORE_STRUCT),
            "::",
            stringify!(tx_semaphore_id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_semaphore_name) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_SEMAPHORE_STRUCT),
            "::",
            stringify!(tx_semaphore_name)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_semaphore_count) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_SEMAPHORE_STRUCT),
            "::",
            stringify!(tx_semaphore_count)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_semaphore_suspension_list) as usize - ptr as usize
        },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_SEMAPHORE_STRUCT),
            "::",
            stringify!(tx_semaphore_suspension_list)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_semaphore_suspended_count) as usize - ptr as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_SEMAPHORE_STRUCT),
            "::",
            stringify!(tx_semaphore_suspended_count)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_semaphore_created_next) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_SEMAPHORE_STRUCT),
            "::",
            stringify!(tx_semaphore_created_next)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).tx_semaphore_created_previous) as usize - ptr as usize
        },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_SEMAPHORE_STRUCT),
            "::",
            stringify!(tx_semaphore_created_previous)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tx_semaphore_put_notify) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(TX_SEMAPHORE_STRUCT),
            "::",
            stringify!(tx_semaphore_put_notify)
        )
    );
}
pub type TX_SEMAPHORE = TX_SEMAPHORE_STRUCT;
extern "C" {
    pub fn tx_application_define(first_unused_memory: *mut ::core::ffi::c_void);
}
extern "C" {
    pub fn _tx_block_allocate(
        pool_ptr: *mut TX_BLOCK_POOL,
        block_ptr: *mut *mut ::core::ffi::c_void,
        wait_option: ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_block_pool_create(
        pool_ptr: *mut TX_BLOCK_POOL,
        name_ptr: *mut CHAR,
        block_size: ULONG,
        pool_start: *mut ::core::ffi::c_void,
        pool_size: ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_block_pool_delete(pool_ptr: *mut TX_BLOCK_POOL) -> UINT;
}
extern "C" {
    pub fn _tx_block_pool_info_get(
        pool_ptr: *mut TX_BLOCK_POOL,
        name: *mut *mut CHAR,
        available_blocks: *mut ULONG,
        total_blocks: *mut ULONG,
        first_suspended: *mut *mut TX_THREAD,
        suspended_count: *mut ULONG,
        next_pool: *mut *mut TX_BLOCK_POOL,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_block_pool_performance_info_get(
        pool_ptr: *mut TX_BLOCK_POOL,
        allocates: *mut ULONG,
        releases: *mut ULONG,
        suspensions: *mut ULONG,
        timeouts: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_block_pool_performance_system_info_get(
        allocates: *mut ULONG,
        releases: *mut ULONG,
        suspensions: *mut ULONG,
        timeouts: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_block_pool_prioritize(pool_ptr: *mut TX_BLOCK_POOL) -> UINT;
}
extern "C" {
    pub fn _tx_block_release(block_ptr: *mut ::core::ffi::c_void) -> UINT;
}
extern "C" {
    pub fn _tx_byte_allocate(
        pool_ptr: *mut TX_BYTE_POOL,
        memory_ptr: *mut *mut ::core::ffi::c_void,
        memory_size: ULONG,
        wait_option: ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_byte_pool_create(
        pool_ptr: *mut TX_BYTE_POOL,
        name_ptr: *mut CHAR,
        pool_start: *mut ::core::ffi::c_void,
        pool_size: ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_byte_pool_delete(pool_ptr: *mut TX_BYTE_POOL) -> UINT;
}
extern "C" {
    pub fn _tx_byte_pool_info_get(
        pool_ptr: *mut TX_BYTE_POOL,
        name: *mut *mut CHAR,
        available_bytes: *mut ULONG,
        fragments: *mut ULONG,
        first_suspended: *mut *mut TX_THREAD,
        suspended_count: *mut ULONG,
        next_pool: *mut *mut TX_BYTE_POOL,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_byte_pool_performance_info_get(
        pool_ptr: *mut TX_BYTE_POOL,
        allocates: *mut ULONG,
        releases: *mut ULONG,
        fragments_searched: *mut ULONG,
        merges: *mut ULONG,
        splits: *mut ULONG,
        suspensions: *mut ULONG,
        timeouts: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_byte_pool_performance_system_info_get(
        allocates: *mut ULONG,
        releases: *mut ULONG,
        fragments_searched: *mut ULONG,
        merges: *mut ULONG,
        splits: *mut ULONG,
        suspensions: *mut ULONG,
        timeouts: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_byte_pool_prioritize(pool_ptr: *mut TX_BYTE_POOL) -> UINT;
}
extern "C" {
    pub fn _tx_byte_release(memory_ptr: *mut ::core::ffi::c_void) -> UINT;
}
extern "C" {
    pub fn _tx_event_flags_create(
        group_ptr: *mut TX_EVENT_FLAGS_GROUP,
        name_ptr: *mut CHAR,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_event_flags_delete(group_ptr: *mut TX_EVENT_FLAGS_GROUP) -> UINT;
}
extern "C" {
    pub fn _tx_event_flags_get(
        group_ptr: *mut TX_EVENT_FLAGS_GROUP,
        requested_flags: ULONG,
        get_option: UINT,
        actual_flags_ptr: *mut ULONG,
        wait_option: ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_event_flags_info_get(
        group_ptr: *mut TX_EVENT_FLAGS_GROUP,
        name: *mut *mut CHAR,
        current_flags: *mut ULONG,
        first_suspended: *mut *mut TX_THREAD,
        suspended_count: *mut ULONG,
        next_group: *mut *mut TX_EVENT_FLAGS_GROUP,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_event_flags_performance_info_get(
        group_ptr: *mut TX_EVENT_FLAGS_GROUP,
        sets: *mut ULONG,
        gets: *mut ULONG,
        suspensions: *mut ULONG,
        timeouts: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_event_flags_performance_system_info_get(
        sets: *mut ULONG,
        gets: *mut ULONG,
        suspensions: *mut ULONG,
        timeouts: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_event_flags_set(
        group_ptr: *mut TX_EVENT_FLAGS_GROUP,
        flags_to_set: ULONG,
        set_option: UINT,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_event_flags_set_notify(
        group_ptr: *mut TX_EVENT_FLAGS_GROUP,
        events_set_notify: ::core::option::Option<
            unsafe extern "C" fn(notify_group_ptr: *mut TX_EVENT_FLAGS_GROUP),
        >,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_initialize_kernel_enter();
}
extern "C" {
    pub fn _tx_mutex_create(mutex_ptr: *mut TX_MUTEX, name_ptr: *mut CHAR, inherit: UINT) -> UINT;
}
extern "C" {
    pub fn _tx_mutex_delete(mutex_ptr: *mut TX_MUTEX) -> UINT;
}
extern "C" {
    pub fn _tx_mutex_get(mutex_ptr: *mut TX_MUTEX, wait_option: ULONG) -> UINT;
}
extern "C" {
    pub fn _tx_mutex_info_get(
        mutex_ptr: *mut TX_MUTEX,
        name: *mut *mut CHAR,
        count: *mut ULONG,
        owner: *mut *mut TX_THREAD,
        first_suspended: *mut *mut TX_THREAD,
        suspended_count: *mut ULONG,
        next_mutex: *mut *mut TX_MUTEX,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_mutex_performance_info_get(
        mutex_ptr: *mut TX_MUTEX,
        puts: *mut ULONG,
        gets: *mut ULONG,
        suspensions: *mut ULONG,
        timeouts: *mut ULONG,
        inversions: *mut ULONG,
        inheritances: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_mutex_performance_system_info_get(
        puts: *mut ULONG,
        gets: *mut ULONG,
        suspensions: *mut ULONG,
        timeouts: *mut ULONG,
        inversions: *mut ULONG,
        inheritances: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_mutex_prioritize(mutex_ptr: *mut TX_MUTEX) -> UINT;
}
extern "C" {
    pub fn _tx_mutex_put(mutex_ptr: *mut TX_MUTEX) -> UINT;
}
extern "C" {
    pub fn _tx_queue_create(
        queue_ptr: *mut TX_QUEUE,
        name_ptr: *mut CHAR,
        message_size: UINT,
        queue_start: *mut ::core::ffi::c_void,
        queue_size: ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_queue_delete(queue_ptr: *mut TX_QUEUE) -> UINT;
}
extern "C" {
    pub fn _tx_queue_flush(queue_ptr: *mut TX_QUEUE) -> UINT;
}
extern "C" {
    pub fn _tx_queue_info_get(
        queue_ptr: *mut TX_QUEUE,
        name: *mut *mut CHAR,
        enqueued: *mut ULONG,
        available_storage: *mut ULONG,
        first_suspended: *mut *mut TX_THREAD,
        suspended_count: *mut ULONG,
        next_queue: *mut *mut TX_QUEUE,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_queue_performance_info_get(
        queue_ptr: *mut TX_QUEUE,
        messages_sent: *mut ULONG,
        messages_received: *mut ULONG,
        empty_suspensions: *mut ULONG,
        full_suspensions: *mut ULONG,
        full_errors: *mut ULONG,
        timeouts: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_queue_performance_system_info_get(
        messages_sent: *mut ULONG,
        messages_received: *mut ULONG,
        empty_suspensions: *mut ULONG,
        full_suspensions: *mut ULONG,
        full_errors: *mut ULONG,
        timeouts: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_queue_prioritize(queue_ptr: *mut TX_QUEUE) -> UINT;
}
extern "C" {
    pub fn _tx_queue_receive(
        queue_ptr: *mut TX_QUEUE,
        destination_ptr: *mut ::core::ffi::c_void,
        wait_option: ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_queue_send(
        queue_ptr: *mut TX_QUEUE,
        source_ptr: *mut ::core::ffi::c_void,
        wait_option: ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_queue_send_notify(
        queue_ptr: *mut TX_QUEUE,
        queue_send_notify: ::core::option::Option<
            unsafe extern "C" fn(notify_queue_ptr: *mut TX_QUEUE),
        >,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_queue_front_send(
        queue_ptr: *mut TX_QUEUE,
        source_ptr: *mut ::core::ffi::c_void,
        wait_option: ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_semaphore_ceiling_put(semaphore_ptr: *mut TX_SEMAPHORE, ceiling: ULONG) -> UINT;
}
extern "C" {
    pub fn _tx_semaphore_create(
        semaphore_ptr: *mut TX_SEMAPHORE,
        name_ptr: *mut CHAR,
        initial_count: ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_semaphore_delete(semaphore_ptr: *mut TX_SEMAPHORE) -> UINT;
}
extern "C" {
    pub fn _tx_semaphore_get(semaphore_ptr: *mut TX_SEMAPHORE, wait_option: ULONG) -> UINT;
}
extern "C" {
    pub fn _tx_semaphore_info_get(
        semaphore_ptr: *mut TX_SEMAPHORE,
        name: *mut *mut CHAR,
        current_value: *mut ULONG,
        first_suspended: *mut *mut TX_THREAD,
        suspended_count: *mut ULONG,
        next_semaphore: *mut *mut TX_SEMAPHORE,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_semaphore_performance_info_get(
        semaphore_ptr: *mut TX_SEMAPHORE,
        puts: *mut ULONG,
        gets: *mut ULONG,
        suspensions: *mut ULONG,
        timeouts: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_semaphore_performance_system_info_get(
        puts: *mut ULONG,
        gets: *mut ULONG,
        suspensions: *mut ULONG,
        timeouts: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_semaphore_prioritize(semaphore_ptr: *mut TX_SEMAPHORE) -> UINT;
}
extern "C" {
    pub fn _tx_semaphore_put(semaphore_ptr: *mut TX_SEMAPHORE) -> UINT;
}
extern "C" {
    pub fn _tx_semaphore_put_notify(
        semaphore_ptr: *mut TX_SEMAPHORE,
        semaphore_put_notify: ::core::option::Option<
            unsafe extern "C" fn(notify_semaphore_ptr: *mut TX_SEMAPHORE),
        >,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_thread_context_save();
}
extern "C" {
    pub fn _tx_thread_context_restore();
}
extern "C" {
    pub fn _tx_thread_create(
        thread_ptr: *mut TX_THREAD,
        name_ptr: *mut CHAR,
        entry_function: ::core::option::Option<unsafe extern "C" fn(entry_input: ULONG)>,
        entry_input: ULONG,
        stack_start: *mut ::core::ffi::c_void,
        stack_size: ULONG,
        priority: UINT,
        preempt_threshold: UINT,
        time_slice: ULONG,
        auto_start: UINT,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_thread_delete(thread_ptr: *mut TX_THREAD) -> UINT;
}
extern "C" {
    pub fn _tx_thread_entry_exit_notify(
        thread_ptr: *mut TX_THREAD,
        thread_entry_exit_notify: ::core::option::Option<
            unsafe extern "C" fn(notify_thread_ptr: *mut TX_THREAD, type_: UINT),
        >,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_thread_identify() -> *mut TX_THREAD;
}
extern "C" {
    pub fn _tx_thread_info_get(
        thread_ptr: *mut TX_THREAD,
        name: *mut *mut CHAR,
        state: *mut UINT,
        run_count: *mut ULONG,
        priority: *mut UINT,
        preemption_threshold: *mut UINT,
        time_slice: *mut ULONG,
        next_thread: *mut *mut TX_THREAD,
        next_suspended_thread: *mut *mut TX_THREAD,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_thread_interrupt_control(new_posture: UINT) -> UINT;
}
extern "C" {
    pub fn _tx_thread_performance_info_get(
        thread_ptr: *mut TX_THREAD,
        resumptions: *mut ULONG,
        suspensions: *mut ULONG,
        solicited_preemptions: *mut ULONG,
        interrupt_preemptions: *mut ULONG,
        priority_inversions: *mut ULONG,
        time_slices: *mut ULONG,
        relinquishes: *mut ULONG,
        timeouts: *mut ULONG,
        wait_aborts: *mut ULONG,
        last_preempted_by: *mut *mut TX_THREAD,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_thread_performance_system_info_get(
        resumptions: *mut ULONG,
        suspensions: *mut ULONG,
        solicited_preemptions: *mut ULONG,
        interrupt_preemptions: *mut ULONG,
        priority_inversions: *mut ULONG,
        time_slices: *mut ULONG,
        relinquishes: *mut ULONG,
        timeouts: *mut ULONG,
        wait_aborts: *mut ULONG,
        non_idle_returns: *mut ULONG,
        idle_returns: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_thread_preemption_change(
        thread_ptr: *mut TX_THREAD,
        new_threshold: UINT,
        old_threshold: *mut UINT,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_thread_priority_change(
        thread_ptr: *mut TX_THREAD,
        new_priority: UINT,
        old_priority: *mut UINT,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_thread_relinquish();
}
extern "C" {
    pub fn _tx_thread_reset(thread_ptr: *mut TX_THREAD) -> UINT;
}
extern "C" {
    pub fn _tx_thread_resume(thread_ptr: *mut TX_THREAD) -> UINT;
}
extern "C" {
    pub fn _tx_thread_sleep(timer_ticks: ULONG) -> UINT;
}
extern "C" {
    pub fn _tx_thread_stack_error_notify(
        stack_error_handler: ::core::option::Option<
            unsafe extern "C" fn(thread_ptr: *mut TX_THREAD),
        >,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_thread_suspend(thread_ptr: *mut TX_THREAD) -> UINT;
}
extern "C" {
    pub fn _tx_thread_terminate(thread_ptr: *mut TX_THREAD) -> UINT;
}
extern "C" {
    pub fn _tx_thread_time_slice_change(
        thread_ptr: *mut TX_THREAD,
        new_time_slice: ULONG,
        old_time_slice: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_thread_wait_abort(thread_ptr: *mut TX_THREAD) -> UINT;
}
extern "C" {
    pub fn _tx_timer_activate(timer_ptr: *mut TX_TIMER) -> UINT;
}
extern "C" {
    pub fn _tx_timer_change(
        timer_ptr: *mut TX_TIMER,
        initial_ticks: ULONG,
        reschedule_ticks: ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_timer_create(
        timer_ptr: *mut TX_TIMER,
        name_ptr: *mut CHAR,
        expiration_function: ::core::option::Option<unsafe extern "C" fn(input: ULONG)>,
        expiration_input: ULONG,
        initial_ticks: ULONG,
        reschedule_ticks: ULONG,
        auto_activate: UINT,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_timer_deactivate(timer_ptr: *mut TX_TIMER) -> UINT;
}
extern "C" {
    pub fn _tx_timer_delete(timer_ptr: *mut TX_TIMER) -> UINT;
}
extern "C" {
    pub fn _tx_timer_info_get(
        timer_ptr: *mut TX_TIMER,
        name: *mut *mut CHAR,
        active: *mut UINT,
        remaining_ticks: *mut ULONG,
        reschedule_ticks: *mut ULONG,
        next_timer: *mut *mut TX_TIMER,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_timer_performance_info_get(
        timer_ptr: *mut TX_TIMER,
        activates: *mut ULONG,
        reactivates: *mut ULONG,
        deactivates: *mut ULONG,
        expirations: *mut ULONG,
        expiration_adjusts: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_timer_performance_system_info_get(
        activates: *mut ULONG,
        reactivates: *mut ULONG,
        deactivates: *mut ULONG,
        expirations: *mut ULONG,
        expiration_adjusts: *mut ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_time_get() -> ULONG;
}
extern "C" {
    pub fn _tx_time_set(new_time: ULONG);
}
extern "C" {
    pub fn _tx_trace_enable(
        trace_buffer_start: *mut ::core::ffi::c_void,
        trace_buffer_size: ULONG,
        registry_entries: ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_trace_event_filter(event_filter_bits: ULONG) -> UINT;
}
extern "C" {
    pub fn _tx_trace_event_unfilter(event_unfilter_bits: ULONG) -> UINT;
}
extern "C" {
    pub fn _tx_trace_disable() -> UINT;
}
extern "C" {
    pub fn _tx_trace_isr_enter_insert(isr_id: ULONG);
}
extern "C" {
    pub fn _tx_trace_isr_exit_insert(isr_id: ULONG);
}
extern "C" {
    pub fn _tx_trace_buffer_full_notify(
        full_buffer_callback: ::core::option::Option<
            unsafe extern "C" fn(buffer: *mut ::core::ffi::c_void),
        >,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_trace_user_event_insert(
        event_id: ULONG,
        info_field_1: ULONG,
        info_field_2: ULONG,
        info_field_3: ULONG,
        info_field_4: ULONG,
    ) -> UINT;
}
extern "C" {
    pub fn _tx_trace_interrupt_control(new_posture: UINT) -> UINT;
}
